/*

Although they look asynchronous, yield statements are actually synscronous.
Use the `.throw` method to throw an error from the place where the last yield
was called (i think? TODO: add throw example)

*/